%YAML:1.0
---
image_width:  1600
image_height: 1200

# --------------------------------------------------------------------------
# Left camera intrinsic matrix K1 (3x3)
#   [fx  0  cx]
#   [ 0 fy  cy]
#   [ 0  0   1]
# --------------------------------------------------------------------------
K1: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 810.7496, 0.0000, 781.6877,
          0.0000, 809.5877, 602.2403,
          0.0000, 0.0000, 1.0000 ]

# --------------------------------------------------------------------------
# Left distortion coefficients D1 (1x5: k1, k2, p1, p2, k3)
# --------------------------------------------------------------------------
D1: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [ -0.047957124, 0.1040098, 3.567703e-05, -0.00043709176, -0.052235563 ]

# --------------------------------------------------------------------------
# Right camera intrinsic matrix K2 (3x3)
# --------------------------------------------------------------------------
K2: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 807.9392, 0.0000, 781.4277,
          0.0000, 806.8987, 604.9526,
          0.0000, 0.0000, 1.0000 ]

# --------------------------------------------------------------------------
# Right distortion coefficients D2 (1x5: k1, k2, p1, p2, k3)
# --------------------------------------------------------------------------
D2: !!opencv-matrix
  rows: 1
  cols: 5
  dt: d
  data: [ -0.064155667, 0.14578241, 0.0009871443,-0.0008595034, -0.082541663 ]

# --------------------------------------------------------------------------
# Rotation of RIGHT camera w.r.t. LEFT camera (3x3)
# From cv::stereoCalibrate output R matrix
# --------------------------------------------------------------------------
R: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 0.999945615718, 0.00862037999687, -0.00586980881925, 
          -0.00859353767876, 0.999952572878, 0.00458291445429,   
          0.0059090368952, -0.00453222279252, 0.999972270735 ]

# --------------------------------------------------------------------------
# Translation of RIGHT camera w.r.t. LEFT camera (3x1, METRES)
# From cv::stereoCalibrate output T vector
# --------------------------------------------------------------------------
T: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [ -0.199715547535, 0.00100174068916, -0.000636642368945 ]
